#!/bin/sh
#
# Check that no files with blanks, quotes, or backslahes in them are added,
# these would break other hook scripts;
# also anything that git considers "unusual" characters and leads to
# quoting will break most commands. So let's break out early.
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

IFS=$'\n'
git diff --name-only --cached --diff-filter=ACRM | ( # sub-shell so we can set -- ${var}
	fail=0
	while read -r filename ; do
		case "${filename}" in
		*[\'\"\\]*)
			pre_commit_error "File name $(printf %s "${filename}" | sed 's,\\,\\\\,g') contains invalid characters. Rename the file."
			fail=1
			;;
		esac
		IFS=$' \a\b\f\r\t\v'
		# shellcheck disable=SC2086 # we do want to split ${filename} here
		set -- ${filename}
		if [ $# -gt 1 ] ; then
			pre_commit_error "File name '${filename}' contains whitespace. Rename the file."
			fail=1
		fi
	done
	if [ ${fail} -ne 0 ] && [ -n "${PRE_COMMIT_KEEP_GOING}" ] ; then
		pre_commit_error "Note that subsequent test scripts in this pre-commit hook may fail to access such files."
	fi
	exit ${fail}
) || exit $?
