#!/bin/sh
#
# Check that Mk/ files are properly indented
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

check_indentation() {
	local mkfile name tempdir
	mkfile="$1"
	name="${mkfile##*/}"
	if ! tempdir="$(mktemp -d -t "check_indentations-${name}")" ; then
		echo "[pre-commit] Failed to create tempdir"
		exit 2
	fi
	if ! cp "${mkfile}" "${tempdir}" || ! Tools/scripts/indent_make_if.pl "${tempdir}/${name}" ; then
		pre_commit_error "Failed to run Tools/scripts/indent_make_if.pl"
		exit 2
	fi
	if ! cmp -s "${tempdir}"/* ; then
		pre_commit_error "File '${mkfile}' is not properly indented"
		error "                    Please use '${tempdir}/${name}',"
	        error "                    which was created using Tools/scripts/indent_make_if.pl"
		exit 1
	fi
}

IFS=$'\n'
set -o pipefail
if modified_mks=$(git diff --name-only --cached --diff-filter=ACRM | grep -E '^Mk/.*\.mk$') ; then
	for modified_mk in ${modified_mks} ; do
		check_indentation "${modified_mk}"
	done
fi
