#!/bin/sh
#
# Check that ports do not contain a 'Created by' tag
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

makefiles=$(git diff --name-only --cached --diff-filter=ACMR | grep -E '^[^/]+/[^/]+/Makefile$')
if [ $? -eq 0 ] ; then
	IFS=$'\n'
	for makefile in ${makefiles} ; do
		read -r firstline <${makefile}
		case "${firstline}"
		in *"Created by"*:*)
			pre_commit_error "${makefile} contains obsolete 'Created by' line\n" \
			        "                   Please remove the the line, and append:\n\n" \
			        "                   - Removed 'Created by ${created_by}'.\n\n" \
			        "                   to your commit message."
			exit 1
			;;
		esac
	done
fi
