#!/bin/sh
#
# Check that only standard files are added to a port
#
#    .*\.mk
#    Makefile.*
#    distinfo.*
#    pkg-.*
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

status=0
set -o pipefail
category_regex="($(make -VSUBDIR | sed 's# #\|#g'))" || exit 2
if newish_files=$(git diff --name-only --cached --diff-filter=ACR | grep -E "^${category_regex}/[^/]+/[^/]+$") ; then
	IFS=$'\n'
	for newish_file in ${newish_files} ; do
		IFS=/ read -r category port file <<-EOT
			$(printf %s "${newish_file}")
		EOT
		case "${file}" in
		Makefile*|distinfo*|pkg-*|*.mk)
			# these are good
			;;
		*)
			pre_commit_error "invalid file '${file}' in '${category}/${port}'"
			status=1
			;;
	esac
	done
fi
if [ ${status} -ne 0 ] ; then
	error "             Consider moving non-standard files to files/ or force-ignore this hook."
	exit ${status}
fi
