#!/bin/sh
#
# Check that no files with blanks, quotes, or backslahes in them are added,
# these would break other hook scripts
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

IFS=$'\n'
git diff --name-only --cached --diff-filter=ACRM | \
(
	fail=0
	while read -r filename ; do
		case "$filename" in
		*[\'\"\\]*)
			pre_commit_error "File name $(printf %s "$filename" | sed 's,\\,\\\\,g') contains invalid characters. Rename the file."
			fail=1
			;;
		esac
		IFS=$' \t'
		set -- $filename
		if [ $# -gt 1 ] ; then
			pre_commit_error "File name '$filename' contains whitespace. Rename the file."
			fail=1
		fi
	done
	exit ${fail}
) || exit $?
