#!/bin/sh
#
# Check that newly added MOVED lines are valid
# uses Tools/script/MOVEDlint.awk
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

if [ -n "$(git diff --cached --name-only --diff-filter=M -- 'MOVED')" ] ; then
	# git changes to root directory of the tree to run hooks
	tree=$(git rev-parse --show-toplevel)
	# check the last seven days
	lastdate=$(date -v-7d "+%Y-%m-%d")

	if ! errors=$(PORTSDIR=${tree} Tools/scripts/MOVEDlint.awk -v lastdate="${lastdate}") ; then
		pre_commit_error "MOVED contains errors.\n" \
			"                   Please apply the suggested changes:\n"
		error "${errors}"
		exit 1
	fi
fi
