#!/bin/sh
#
# Check that ports do not contain a 'Created by' tag
#

common_functions="$(realpath "$(dirname "$0")")/common.sh"
if [ -r "${common_functions}" ]; then
	. "${common_functions}"
fi

if makefiles=$(git diff --name-only --cached --diff-filter=ACMR | grep -E '^[^/]+/[^/]+/Makefile$') ; then
	IFS=$'\n'
	for makefile in ${makefiles} ; do
		IFS=:
		read -r tag created_by <<-EOT
			$(head -n1 "${makefile}")
		EOT
		case "${tag}" in *"Created by"*)
			pre_commit_error "File ${makefile} contains an obsolete 'Created by' line\n" \
			        "                   Please remove the line, and append:\n\n" \
			        "                   - Removed 'Created by:${created_by}'.\n\n" \
			        "                   to your commit message."
			exit 1
			;;
		esac
	done
fi
